server:
  address: 0.0.0.0
  port: ${PORT:8080}
  servlet.context-path: /event-api
  error.whitelabel.enabled: false

spring:
  application:
    name: event-api
  mvc:
    throw-exception-if-no-handler-found: false
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/events"
    username: postgres
    password: "Ujkjcjdfzgjxnf8"